version: "3"
services:
  db:
    restart: always
    image: "postgres:11-alpine"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - default

  web:
    privileged: true
    build: .
    restart: always
    env_file:
      - ./.env
    command: "gunicorn --bind 0.0.0.0:8080 LearningCards.wsgi"
    volumes:
      - .:/LearningCards
      - /sys:/sys
    depends_on:
      - db
    networks:
      - default

  nginx:
    image: "nginx"
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./staticfiles:/static
      - ./mediafiles:/media
    networks:
      - default
      - nginx-proxy

networks:
  default:
  nginx-proxy:
    external:
      name: nginx-proxy
