version: "3"
services:
  db:
    restart: always
    image: "postgres:11-alpine"
    volumes:
    - ./postgresql:/var/lib/postgresql/data
    env_file:
    - ./.env

  web:
    privileged: true
    build: .
    restart: always
    env_file:
    - ./.env
    command: "gunicorn --bind 0.0.0.0:8080 LearningCards.wsgi"
    volumes:
    - .:/LearningCards
    - /sys:/sys
    depends_on:
    - db

  nginx_pigpio:
    image: "nginx"
    restart: always
    env_file:
    - ./.env
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
    - ./staticfiles:/static
    - ./mediafiles:/media
    ports:
      - "80:80"