# Generated by Django 3.0.2 on 2020-01-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0002_auto_20200127_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
