# Generated by Django 3.0.2 on 2020-01-29 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0006_test_testquestions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestQuestions',
            new_name='TestQuestion',
        ),
    ]
