# Generated by Django 3.0.2 on 2020-01-29 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0007_auto_20200129_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Cards.Course'),
            preserve_default=False,
        ),
    ]
