# Generated by Django 3.0.2 on 2020-01-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0008_test_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
