# Generated by Django 3.0.2 on 2020-01-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0009_testquestion_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testquestion',
            name='completed',
        ),
        migrations.AddField(
            model_name='test',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
