# Generated by Django 3.0.2 on 2020-02-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0011_auto_20200203_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='source',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
