# Generated by Django 3.0.5 on 2020-04-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0013_course_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32)),
                ('info', models.TextField()),
                ('valid_until', models.DateTimeField()),
            ],
        ),
    ]
