# Generated by Django 3.0.5 on 2020-04-20 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('Cards', '0014_registrationkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('signup_key', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='Cards.RegistrationKey')),
            ],
        ),
    ]
