# Generated by Django 3.0.5 on 2020-04-20 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0015_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='signup_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Cards.RegistrationKey'),
        ),
    ]
