# Generated by Django 3.0.5 on 2020-04-20 15:03

from django.db import migrations


def create_user_info(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserInfo = apps.get_model('Cards', 'UserInfo')
    for u in User.objects.all():
        UserInfo.objects.create(user=u)


class Migration(migrations.Migration):
    dependencies = [
        ('Cards', '0016_auto_20200420_1703'),
    ]

    operations = [
        migrations.RunPython(create_user_info)
    ]
