# Generated by Django 5.0.9 on 2024-11-14 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0018_alter_questionlog_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='University',
            new_name='Institution',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='university',
            new_name='institution',
        ),
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
    ]
