# Generated by Django 5.0.9 on 2024-11-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cards', '0019_rename_university_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='course',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('V_NON_PUBLIC', 'Not Public')], default='PUBLIC', max_length=128),
        ),
    ]
